package com.ruoyi.business.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_appraise
 *
 * @mbg.generated do_not_delete_during_merge Wed Apr 22 12:41:12 CST 2020
 */
public class Appraise {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.id
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   预约信息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.reverse_info_id
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private Integer reverseInfoId;

    /**
     * Database Column Remarks:
     *   台面清洁评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.clean_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private Integer cleanNum;

    /**
     * Database Column Remarks:
     *   球台完整评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.qiu_tai_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private Integer qiuTaiNum;

    /**
     * Database Column Remarks:
     *   室内温度评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.temp_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private Integer tempNum;

    /**
     * Database Column Remarks:
     *   其他建议
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.comment
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private String comment;

    /**
     * Database Column Remarks:
     *   评价时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_appraise.appraise_time
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    private Date appraiseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.id
     *
     * @return the value of t_appraise.id
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.id
     *
     * @param id the value for t_appraise.id
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.reverse_info_id
     *
     * @return the value of t_appraise.reverse_info_id
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public Integer getReverseInfoId() {
        return reverseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.reverse_info_id
     *
     * @param reverseInfoId the value for t_appraise.reverse_info_id
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setReverseInfoId(Integer reverseInfoId) {
        this.reverseInfoId = reverseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.clean_num
     *
     * @return the value of t_appraise.clean_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public Integer getCleanNum() {
        return cleanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.clean_num
     *
     * @param cleanNum the value for t_appraise.clean_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setCleanNum(Integer cleanNum) {
        this.cleanNum = cleanNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.qiu_tai_num
     *
     * @return the value of t_appraise.qiu_tai_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public Integer getQiuTaiNum() {
        return qiuTaiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.qiu_tai_num
     *
     * @param qiuTaiNum the value for t_appraise.qiu_tai_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setQiuTaiNum(Integer qiuTaiNum) {
        this.qiuTaiNum = qiuTaiNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.temp_num
     *
     * @return the value of t_appraise.temp_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public Integer getTempNum() {
        return tempNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.temp_num
     *
     * @param tempNum the value for t_appraise.temp_num
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setTempNum(Integer tempNum) {
        this.tempNum = tempNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.comment
     *
     * @return the value of t_appraise.comment
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.comment
     *
     * @param comment the value for t_appraise.comment
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_appraise.appraise_time
     *
     * @return the value of t_appraise.appraise_time
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public Date getAppraiseTime() {
        return appraiseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_appraise.appraise_time
     *
     * @param appraiseTime the value for t_appraise.appraise_time
     *
     * @mbg.generated Wed Apr 22 12:41:12 CST 2020
     */
    public void setAppraiseTime(Date appraiseTime) {
        this.appraiseTime = appraiseTime;
    }
}