package com.ruoyi.business.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_reverse_info
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 14 17:18:58 CST 2020
 */
public class ReverseInfo {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   球台ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.table_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Integer tableId;

    /**
     * Database Column Remarks:
     *   学生ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.user_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   学生ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.student_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Integer studentId;

    /**
     * Database Column Remarks:
     *   预定开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.reverse_start_tm
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Date reverseStartTm;

    /**
     * Database Column Remarks:
     *   预定结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.reverse_end_tm
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Date reverseEndTm;

    /**
     * Database Column Remarks:
     *   状态  0 -未审批  1-同意  2-已拒绝
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.status
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   验证码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_reverse_info.ver_code
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    private String verCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.id
     *
     * @return the value of t_reverse_info.id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.id
     *
     * @param id the value for t_reverse_info.id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.table_id
     *
     * @return the value of t_reverse_info.table_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.table_id
     *
     * @param tableId the value for t_reverse_info.table_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.user_id
     *
     * @return the value of t_reverse_info.user_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.user_id
     *
     * @param userId the value for t_reverse_info.user_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.student_id
     *
     * @return the value of t_reverse_info.student_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.student_id
     *
     * @param studentId the value for t_reverse_info.student_id
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.reverse_start_tm
     *
     * @return the value of t_reverse_info.reverse_start_tm
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Date getReverseStartTm() {
        return reverseStartTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.reverse_start_tm
     *
     * @param reverseStartTm the value for t_reverse_info.reverse_start_tm
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setReverseStartTm(Date reverseStartTm) {
        this.reverseStartTm = reverseStartTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.reverse_end_tm
     *
     * @return the value of t_reverse_info.reverse_end_tm
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Date getReverseEndTm() {
        return reverseEndTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.reverse_end_tm
     *
     * @param reverseEndTm the value for t_reverse_info.reverse_end_tm
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setReverseEndTm(Date reverseEndTm) {
        this.reverseEndTm = reverseEndTm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.status
     *
     * @return the value of t_reverse_info.status
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.status
     *
     * @param status the value for t_reverse_info.status
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_reverse_info.ver_code
     *
     * @return the value of t_reverse_info.ver_code
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public String getVerCode() {
        return verCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_reverse_info.ver_code
     *
     * @param verCode the value for t_reverse_info.ver_code
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setVerCode(String verCode) {
        this.verCode = verCode;
    }
}