package com.ruoyi.business.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ReverseInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public ReverseInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTableIdIsNull() {
            addCriterion("table_id is null");
            return (Criteria) this;
        }

        public Criteria andTableIdIsNotNull() {
            addCriterion("table_id is not null");
            return (Criteria) this;
        }

        public Criteria andTableIdEqualTo(Integer value) {
            addCriterion("table_id =", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotEqualTo(Integer value) {
            addCriterion("table_id <>", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdGreaterThan(Integer value) {
            addCriterion("table_id >", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("table_id >=", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdLessThan(Integer value) {
            addCriterion("table_id <", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdLessThanOrEqualTo(Integer value) {
            addCriterion("table_id <=", value, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdIn(List<Integer> values) {
            addCriterion("table_id in", values, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotIn(List<Integer> values) {
            addCriterion("table_id not in", values, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdBetween(Integer value1, Integer value2) {
            addCriterion("table_id between", value1, value2, "tableId");
            return (Criteria) this;
        }

        public Criteria andTableIdNotBetween(Integer value1, Integer value2) {
            addCriterion("table_id not between", value1, value2, "tableId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(Integer value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(Integer value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(Integer value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(Integer value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(Integer value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<Integer> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<Integer> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(Integer value1, Integer value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmIsNull() {
            addCriterion("reverse_start_tm is null");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmIsNotNull() {
            addCriterion("reverse_start_tm is not null");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmEqualTo(Date value) {
            addCriterion("reverse_start_tm =", value, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmNotEqualTo(Date value) {
            addCriterion("reverse_start_tm <>", value, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmGreaterThan(Date value) {
            addCriterion("reverse_start_tm >", value, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmGreaterThanOrEqualTo(Date value) {
            addCriterion("reverse_start_tm >=", value, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmLessThan(Date value) {
            addCriterion("reverse_start_tm <", value, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmLessThanOrEqualTo(Date value) {
            addCriterion("reverse_start_tm <=", value, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmIn(List<Date> values) {
            addCriterion("reverse_start_tm in", values, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmNotIn(List<Date> values) {
            addCriterion("reverse_start_tm not in", values, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmBetween(Date value1, Date value2) {
            addCriterion("reverse_start_tm between", value1, value2, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseStartTmNotBetween(Date value1, Date value2) {
            addCriterion("reverse_start_tm not between", value1, value2, "reverseStartTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmIsNull() {
            addCriterion("reverse_end_tm is null");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmIsNotNull() {
            addCriterion("reverse_end_tm is not null");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmEqualTo(Date value) {
            addCriterion("reverse_end_tm =", value, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmNotEqualTo(Date value) {
            addCriterion("reverse_end_tm <>", value, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmGreaterThan(Date value) {
            addCriterion("reverse_end_tm >", value, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmGreaterThanOrEqualTo(Date value) {
            addCriterion("reverse_end_tm >=", value, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmLessThan(Date value) {
            addCriterion("reverse_end_tm <", value, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmLessThanOrEqualTo(Date value) {
            addCriterion("reverse_end_tm <=", value, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmIn(List<Date> values) {
            addCriterion("reverse_end_tm in", values, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmNotIn(List<Date> values) {
            addCriterion("reverse_end_tm not in", values, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmBetween(Date value1, Date value2) {
            addCriterion("reverse_end_tm between", value1, value2, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andReverseEndTmNotBetween(Date value1, Date value2) {
            addCriterion("reverse_end_tm not between", value1, value2, "reverseEndTm");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andVerCodeIsNull() {
            addCriterion("ver_code is null");
            return (Criteria) this;
        }

        public Criteria andVerCodeIsNotNull() {
            addCriterion("ver_code is not null");
            return (Criteria) this;
        }

        public Criteria andVerCodeEqualTo(String value) {
            addCriterion("ver_code =", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeNotEqualTo(String value) {
            addCriterion("ver_code <>", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeGreaterThan(String value) {
            addCriterion("ver_code >", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ver_code >=", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeLessThan(String value) {
            addCriterion("ver_code <", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeLessThanOrEqualTo(String value) {
            addCriterion("ver_code <=", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeLike(String value) {
            addCriterion("ver_code like", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeNotLike(String value) {
            addCriterion("ver_code not like", value, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeIn(List<String> values) {
            addCriterion("ver_code in", values, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeNotIn(List<String> values) {
            addCriterion("ver_code not in", values, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeBetween(String value1, String value2) {
            addCriterion("ver_code between", value1, value2, "verCode");
            return (Criteria) this;
        }

        public Criteria andVerCodeNotBetween(String value1, String value2) {
            addCriterion("ver_code not between", value1, value2, "verCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_reverse_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Apr 14 17:18:58 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_reverse_info
     *
     * @mbg.generated Tue Apr 14 17:18:58 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}