package com.ruoyi.business.domain;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_user_student
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 14 17:19:42 CST 2020
 */
public class UserStudent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_student.id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_student.user_id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_student.student_id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_student.id
     *
     * @return the value of t_user_student.id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_student.id
     *
     * @param id the value for t_user_student.id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_student.user_id
     *
     * @return the value of t_user_student.user_id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_student.user_id
     *
     * @param userId the value for t_user_student.user_id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_student.student_id
     *
     * @return the value of t_user_student.student_id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_student.student_id
     *
     * @param studentId the value for t_user_student.student_id
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}