package com.ruoyi.business.mapper;

import com.ruoyi.business.domain.UserStudent;
import com.ruoyi.business.domain.UserStudentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    long countByExample(UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int deleteByExample(UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int insert(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int insertSelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    List<UserStudent> selectByExample(UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    UserStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserStudent record, @Param("example") UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int updateByExample(@Param("record") UserStudent record, @Param("example") UserStudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int updateByPrimaryKeySelective(UserStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_student
     *
     * @mbg.generated Tue Apr 14 17:19:42 CST 2020
     */
    int updateByPrimaryKey(UserStudent record);
}